### ISSUE TITLE
Mislabelled 

### ISSUE THREAD

**Issue by MrBrentRogers** [p4535992/foundryvtt-compendiums-mix-dnd5e#1]
um5-ultramodern-ogl is Ultramodern OGL/SRD (UM5)by Dias Ex Machina Games

Well the one labelled as "Ultramodern OGL/SRD (UM5)by Dias Ex Machina Games" is fvtt-me5e (Mass Effect 5e)

**Comment by p4535992** [comment]
Hi Brent thanks for the input. I have updated the readme specifying that this is a personal use project for foundry version 0.8.x and that if you feel "stolen" of your work I will remove it immediately.
